### ISSUE TITLE
problems in CMake lists

### ISSUE THREAD

**Issue by Mikhail2017** [xdspacelab/openvslam#248]
Hi
I'm trying to build on Ubuntu 18.04.
Have created build directory in cloned openvslam folder and succesfully configured a make project. Unfortunately I've got a lot of include errors like this one:

system.cc:1:10: fatal error: openvslam/system.h: No such file or directory
 #include "openvslam/system.h"

Looks like a problem in build scripts

**Comment by shinsumicco** [comment]
@Mikhail2017 
Could you tell us the more details about the commands you used? (from `git clone` to `cmake`)

**Comment by Mikhail2017** [comment]
```
git clone https://github.com/xdspacelab/openvslam
cd openvslam
mkdir build
cd build
cmake .. -DCMAKE_TOOLCHAIN_FILE=~/Coding/vcpkg/scripts/buildsystems/vcpkg.cmake -DUSE_PANGOLIN_VIEWER=OFF -DBUILD_WITH_MARCH_NATIVE=ON -DUSE_SOCKET_PUBLISHER=ON -DUSE_STACK_TRACE_LOGGER=ON -DBOW_FRAMEWORK=DBoW2 -DBUILD_TESTS=ON
make -j4
```

All deps already installed using vcpkg

**Comment by lessthantrue** [comment]
I'm having this same problem. Has anyone found a solution? I'm not experienced enough with Cmake to figure it out myself.
